<a href="https://colab.research.google.com/github/santhozdpi/santhozdpi/blob/main/Numpy_Practice_py.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import numpy as np
import pandas
import seaborn
import matplotlib

arr1 = np.array([1, 2, 3, 4, 5])  # 1D array
arr2 = np.array([[1, 2, 3], [4, 5, 6]])  # 2D array
print(arr1)
print(arr2)
import pandas as pd

# Creating a DataFrame
data = {'Name': ['A', 'B', 'C', 'D'],
        'Age': [25, 30, 35, 40],
        'Salary': [50000, 60000, 70000, 80000]}

df = pd.DataFrame(data)
print(df)

# Accessing Columns
print(df['Name'])

# Descriptive Statistics
print(df.describe())

# Filtering Data
print(df[df['Age'] > 30])




[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
  Name  Age  Salary
0    A   25   50000
1    B   30   60000
2    C   35   70000
3    D   40   80000
0    A
1    B
2    C
3    D
Name: Name, dtype: object
             Age        Salary
count   4.000000      4.000000
mean   32.500000  65000.000000
std     6.454972  12909.944487
min    25.000000  50000.000000
25%    28.750000  57500.000000
50%    32.500000  65000.000000
75%    36.250000  72500.000000
max    40.000000  80000.000000
  Name  Age  Salary
2    C   35   70000
3    D   40   80000


In [8]:
import numpy as np
arr1 = np.array([1, 2, 3, 4, 5])  # 1D array
arr2 = np.array([[1, 2, 3], [4, 5, 6]])  # 2D array
print(arr1)
print(arr2)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
